name: google test
trigger:
  type: manual
steps:
- id: sheets_list_1
  type: sheets_list
  params:
    spreadsheet_id: 1k4FX3oR-ICAgHoFvkd0ZG-nYzY0p3zCahbUcG6BHVts
    credentials_file: C:\Users\winni\my_projects\1\orbit\aptest-384703-24764f69b34f.json
  meta:
    x: 60
    y: 74
- id: sheets_read_1
  type: sheets_read
  params:
    spreadsheet_id: 1k4FX3oR-ICAgHoFvkd0ZG-nYzY0p3zCahbUcG6BHVts
    credentials_file: C:\Users\winni\my_projects\1\orbit\aptest-384703-24764f69b34f.json
    range: tweet!A1:D10
  meta:
    x: 100
    y: 159
- id: ai_generate_1
  type: ai_generate
  params:
    prompt: 次の書き込まれrtweetすべてから人格を創造してください。{{ sheets_read_1.rows }}
  meta:
    x: 119
    y: 239
enabled: true
