name: sample_daily_summary
trigger:
  type: schedule
  cron: "0 9 * * *"
steps:
  - id: fetch_data
    type: log
    params:
      message: "データ取得を開始します"

  - id: process
    type: log
    params:
      message: "データを処理中..."

  - id: notify
    type: log
    params:
      message: "処理が完了しました"
