name: test
trigger:
  type: manual
steps:
- id: ai_generate_1
  type: ai_generate
  params:
    prompt: こんにちは
  meta:
    x: 80
    y: 80
- id: ai_summarize_1
  type: ai_summarize
  params:
    text: '{{ ai_generate_1.text }}'
  meta:
    x: 100
    y: 160
