name: test_every_minute
trigger:
  type: schedule
  cron: "* * * * *"
steps:
  - id: log_time
    type: log
    params:
      message: "Scheduled execution at {{ now }}"

  - id: save_log
    type: file_write
    params:
      path: "runs/output/scheduled_{{ run_id }}.txt"
      content: |
        Scheduled Execution Log
        =======================
        Run ID: {{ run_id }}
        Time: {{ now }}
        Workflow: {{ workflow }}
