name: conditional_step
description: 条件付き分岐のサンプル（前のステップの結果で分岐）
enabled: true
trigger:
  type: manual
steps:
  - id: step_1
    type: log
    params:
      message: "テストメッセージ"
    meta:
      x: 80
      y: 80
  - id: step_2_success
    type: log
    params:
      message: "成功しました"
    meta:
      x: 80
      y: 200
    when:
      step: step_1
      field: logged
      equals: true
  - id: step_3_failure
    type: log
    params:
      message: "失敗しました"
    meta:
      x: 80
      y: 280
    when:
      step: step_1
      field: logged
      equals: false
